export const GOT_SEARCH_RESULTS = 'GOT_SEARCH_RESULTS';
export const GOT_MORE_SEARCH_RESULTS = 'GOT_MORE_SEARCH_RESULTS';
export const GOT_REPO = 'GOT_REPO';
export const GOT_README = 'GOT_README';
export const GOT_URLS = 'GOT_URLS';